### ISSUE TITLE
haze?

### ISSUE THREAD

**Issue by ak1dd** [caligari87/darkdoomz#14]
First, love the mod.

I see there is a fog setting.  I haven't tweaked it to my satisfaction yet.  However in some port specific maps there is a knee-high (appx) layer of haze/fog over liquids.  It looks great.  Any chance you could add a haze?  An option for "all over" and another for "liquids"?

**Comment by caligari87** [comment]
Can you link some examples of mods or maps that do this? Generally in my experience such an needs be built-in to the map, or requires spawning a lot of "fog" actors, both of which are outside the scope of my mod.

**Comment by ak1dd** [comment]
I can't find the specific level I was speaking about... but here is a video of someone who did it with a texture:
https://www.youtube.com/watch?time_continue=34&v=2G9JzXuQZ2I

https://www.doomworld.com/forum/topic/101084-adding-fog-to-level-with-sprite-images/?tab=comments#comment-1887272

**Comment by ak1dd** [comment]
also see similar effects here - https://realm667.com/index.php/en/sfx-shoppe-mainmenu-139-58855/elemental-effects-mainmenu-142-40777#preview-6

**Comment by caligari87** [comment]
Yeah, this is out of scope in my opinion. It's a cool effect but is better hand-placed by a mapper than attempting to auto-generate it and potentially spawn thousands of fog actors.

**Comment by ak1dd** [comment]
OK thanks.  I personally think a MurkyDoomZ with various fog effects would be great.   Trying to find maps that implement environmental effects means few and far between.  Anyway, thanks for your work.
