### ISSUE TITLE
Make mounting locations relative to viewheight

### ISSUE THREAD

**Issue by caligari87** [caligari87/darkdoomz#15]
Requested by Accensus#8937(Lud) on Discord.

> is it possible to have the flashlights' position in DarkDoomZ be affected by the player's viewheight? Cause I've modified the player's viewheight to simulate wearing heavy armor, but the beam (set to Helmet) is coming out of the player's chest. I haven't set the Height property, because it'd mess with map geometry. [...] Worth noting that other mods such as Hearts of Demons - Baron/Revenant also use this viewheight technique, and probably some other famous mods, so it's not uncommon.

This is certainly possible though it will require some minor reworking of the offset code. Right now the offsets are hardcoded to specific heights. Ideally the light source should be as consistent as possible between mods.

**Comment by Accensus** [comment]
I'm thinking some sort of Y/Z adjustment sliders could work well. Y could be in the range [-64, 64] (default: 0) and Z could be [8, 128] (default: 40), both with an increment of either 4 or 8. As for the beam following style, that could be another variable, separated from the offsets. This would add another useful layer of customization.
