### ISSUE TITLE
Prevent darkening of skybox sectors

### ISSUE THREAD

**Issue by Accensus** [caligari87/darkdoomz#16]
Was playing the Sin City 3 wad prior to posting this and noticed that the sky was pitch black due to the use of a skybox sector.

From what I can see, zscript/mapdata.txt may have some info for fixing that, such as the EType enum and mType variable. Whether those are _the_ variables/constants or what the actual implementation would be I can't say for sure.

**Comment by caligari87** [comment]
After further investigation, it appears this cannot be done, at least not without extensive map processing. One particular problem is that skyboxes can consist of multiple sectors, meaning it's not enough to get just any sector with a viewport, I'd also need to get everything the viewport can see.
