### ISSUE TITLE
Flickering Flashlights (like Torch for Heretic and Hexen maps)

### ISSUE THREAD

**Issue by DwarfFighterCleric** [caligari87/darkdoomz#28]
First of all, what a nice mod, nicely done, thanks a lot.  
I was trying to  
modify the ZScript in order to make all the Flashlights behave like Torch Lights (using "Flicker" lights instead of "Point" lights, also disabling Spot flag) Like a "sphere" light instead of flashlight. (at least when I selected the Helmet mount)  
  
I could not get gzdoom to behave the way I wanted when I changed Light properties from "Point" to "Flicker", even adding the parameter SelfLight1.args[LIGHT_SECONDARY.INTENSITY]... The lights would not flicker, they would stay permanently on without oscillating... I even tried using SelfLight1.args[4] but that did not work either  
Any clues on how I could make all the lights Flicker?  
Or at least have the option to make Lights behave that way only when I select Helmet mount (but this is a secondary step)  
  
For now, I have been using the workaround of spawning a Decorate light manually, because I already had the light pasted in from another mod. Using Spawn from Decorate was the only method I could get for the light to Flicker properly (fire light)

**Comment by DwarfFighterCleric** [comment]
Can't find a way to make Flicker Lights behave like Flicker light inside of Zscript code. The lights behave like Point Lights (turned on all the time, with no variation, no oscillation...)  
  
Official Zdoom documentation has nothing on it,  
they only have documentation showing how to do it in Decorate

**Comment by caligari87** [comment]
It's hacky, but you can probably achieve this pretty easily by just randomizing the current intensity value up or down a little every tick in the dynamic light class, and clamping it by your desired bounds.

After line 334, something like the following. I've done this as verbosely as possible so it's clear how it works, but it could probably be made a lot smaller if desired. There may be errors as well, I'm not able to test this at the moment. 
```cs
override void Tick() {
	super.Tick();
	// new stuff starts here
	int upper = 384;
	int lower = 128;
	int current = args[DynamicLight.LIGHT_INTENSITY];
	current += random(-8, 8);
	current = clamp(current, upper, lower);
	args[DynamicLight.LIGHT_INTENSITY] = current;
	// new stuff ends here
	if(followTarget && followTarget.player) {
		if(inertia == 0) inertia = 1;
```
Realistically I could probably add another light type of "torch", or even make some kind of system for easily modding custom light types, but that's a longer-term project I'm not quite ready to tackle.
